-- 코드를 입력하세요
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES FROM BOOK AS b, AUTHOR AS a, BOOK_SALES AS s
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' AND b.AUTHOR_ID=a.AUTHOR_ID 
AND b.BOOK_ID = s.BOOK_ID
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, CATEGORY DESC


